name: VPC deployment in AWS  #Creating a pipeline here
on:
  push:
    branches:
      main
jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Clone our repository
        uses: actions/checkout@v3

      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::880531076845:role/github-actions-oidc
          aws-region: eu-west-1
          role-session-name: GithubVPCDeploy

      - name: Terraform Set up
        uses: hashicorp/setup-terraform@v1

      - name: Terraform initialization
        run: terraform init

      - name: Terraform planning
       run: terraform plan

      - name: Terraform apply
        run: terraform apply -auto-approve